<!-- HTML file automatically generated from DocOnce source (https://github.com/doconce/doconce/)
doconce format html exercisesweek37.do.txt  -->
<!-- dom:TITLE: Exercises week 37 -->

# Exercises week 37
**Implementing gradient descent for Ridge and ordinary Least Squares Regression**

Date: **September 8-12, 2025**

## Learning goals

After having completed these exercises you will have:
1. Your own code for the implementation of the simplest gradient descent approach applied to ordinary least squares (OLS) and Ridge regression

2. Be able to compare the analytical expressions for OLS and Ridge regression with the gradient descent approach

3. Explore the role of the learning rate in the gradient descent approach and the hyperparameter $\lambda$ in Ridge regression

4. Scale the data properly

## Simple one-dimensional second-order polynomial

We start with a very simple function

$$
f(x)= 2-x+5x^2,
$$

defined for $x\in [-2,2]$. You can add noise if you wish. 

We are going to fit this function with a polynomial ansatz. The easiest thing is to set up a second-order polynomial and see if you can fit the above function.
Feel free to play around with higher-order polynomials.

## Exercise 1, scale your data

Before fitting a regression model, it is good practice to normalize or
standardize the features. This ensures all features are on a
comparable scale, which is especially important when using
regularization. Here we will perform standardization, scaling each
feature to have mean 0 and standard deviation 1.

### 1a)

Compute the mean and standard deviation of each column (feature) in your design/feature matrix $\boldsymbol{X}$.
Subtract the mean and divide by the standard deviation for each feature.

We will also center the target $\boldsymbol{y}$ to mean $0$. Centering $\boldsymbol{y}$
(and each feature) means the model does not require a separate intercept
term, the data is shifted such that the intercept is effectively 0
. (In practice, one could include an intercept in the model and not
penalize it, but here we simplify by centering.)
Choose $n=100$ data points and set up $\boldsymbol{x}, $\boldsymbol{y}$ and the design matrix $\boldsymbol{X}$.

In [422]:
import numpy as np

n= 100
x = np.linspace(-2,2,n)
y = 2-x+5*x**2
p=3
lmbda = 0.1

X = np.ones((n, p))
for i in range(p):
    X[:, i] = x ** i

# Standardize features (zero mean, unit variance for each feature)
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
print(X_std)
X_std[X_std == 0] = 1  # safeguard to avoid division by zero for constant features
X_norm = (X - X_mean) / X_std

# Center the target to zero mean (optional, to simplify intercept handling)
y_mean = y.mean()
y_centered = y-y_mean

print(X_mean)
print(X_std)
print(X.shape)

print(X[:,0])



[0.         1.16630586 1.21647937]
[1.00000000e+00 1.28785871e-16 1.36026936e+00]
[1.         1.16630586 1.21647937]
(100, 3)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


Fill in the necessary details.

After this preprocessing, each column of $\boldsymbol{X}_{\mathrm{norm}}$ has mean zero and standard deviation $1$
and $\boldsymbol{y}_{\mathrm{centered}}$ has mean 0. This makes the optimization landscape
nicer and ensures the regularization penalty $\lambda \sum_j
\theta_j^2$ in Ridge regression treats each coefficient fairly (since features are on the
same scale).

## Exercise 2, calculate the gradients

Find the gradients for OLS and Ridge regression using the mean-squared error as cost/loss function.

In [423]:


theta = np.ones(p) 
lmbda = 0.1                #Random starting parameter

def grad_OLS(X, y, theta):
    n = X.shape[0]
    gradient1 = (2.0/n)*X.T @ (X @ theta-y)
    return gradient1

def grad_RIGDE(X, y, theta, lmbda):
    n = X.shape[0]
    gradient2 = 2.0*((1.0/n)*X.T @ ((X @ theta)-y)+lmbda * theta)
    return gradient2

O = grad_OLS(X,y, theta)
R = grad_RIGDE(X,y, theta, lmbda)

print(O)
print(R)

[-12.88215488   5.44107744 -29.36177707]
[-12.68215488   5.64107744 -29.16177707]


## Exercise 3, using the analytical formulae for OLS and Ridge regression to find the optimal paramters $\boldsymbol{\theta}$

In [424]:
# Set regularization parameter, either a single value or a vector of values

# Analytical form for OLS and Ridge solution: theta_Ridge = (X^T X + lambda * I)^{-1} X^T y and theta_OLS = (X^T X)^{-1} X^T y
I = np.eye(p)
lmbda = 0.1


theta_closed_formOLS = np.linalg.inv(X.T @ X) @ (X.T @ y)
theta_closed_formRidge = np.linalg.inv((X.T @ X)+(lmbda*I)) @ (X.T @ y)

print("Closed-form Ridge coefficients:", theta_closed_formOLS)
print("Closed-form OLS coefficients:", theta_closed_formRidge)

Closed-form Ridge coefficients: [ 2. -1.  5.]
Closed-form OLS coefficients: [ 2.00009368 -0.99926539  4.99846076]


This computes the Ridge and OLS regression coefficients directly. The identity
matrix $I$ has the same size as $X^T X$. It adds $\lambda$ to the diagonal of $X^T X$ for Ridge regression. We
then invert this matrix and multiply by $X^T y$. The result
for $\boldsymbol{\theta}$  is a NumPy array of shape (n$\_$features,) containing the
fitted parameters $\boldsymbol{\theta}$.

### 3a)

Finalize, in the above code, the OLS and Ridge regression determination of the optimal parameters $\boldsymbol{\theta}$.

### 3b)

Explore the results as function of different values of the hyperparameter $\lambda$. See for example exercise 4 from week 36.

In [425]:
lambdas = np.logspace(-5, 0, 6)
print(lambdas)
for i in lambdas:
    print("Closed-form OLS coefficients:", np.linalg.inv((X.T @ X)+(i*I)) @ (X.T @ y))


[1.e-05 1.e-04 1.e-03 1.e-02 1.e-01 1.e+00]
Closed-form OLS coefficients: [ 2.00000001 -0.99999993  4.99999985]
Closed-form OLS coefficients: [ 2.0000001  -0.99999926  4.99999846]
Closed-form OLS coefficients: [ 2.00000095 -0.99999265  4.9999846 ]
Closed-form OLS coefficients: [ 2.00000951 -0.99992649  4.99984598]
Closed-form OLS coefficients: [ 2.00009368 -0.99926539  4.99846076]
Closed-form OLS coefficients: [ 2.00079461 -0.99270216  4.98470703]


## Exercise 4, Implementing the simplest form for gradient descent

Alternatively, we can fit the ridge regression model using gradient
descent. This is useful to visualize the iterative convergence and is
necessary if $n$ and $p$ are so large that the closed-form might be
too slow or memory-intensive. We derive the gradients from the cost
functions defined above. Use the gradients of the Ridge and OLS cost functions with respect to
the parameters  $\boldsymbol{\theta}$ and set up (using the template below) your own gradient descent code for OLS and Ridge regression.

Below is a template code for gradient descent implementation of ridge:

In [426]:
# Gradient descent parameters, learning rate eta first
eta = 0.1
# Then number of iterations
num_iters = 1000

# Initialize weights for gradient descent
#p=3
theta_gdOLS = np.ones(p)
theta_gdRidge = np.ones(p)
# Gradient descent loop

for i in range(num_iters):
    # Compute gradients for OSL and Ridge
    OLSgrad = grad_OLS(X, y, theta_gdOLS )
    grad_Ridge = grad_RIGDE(X, y ,theta_gdRidge, lmbda)
    # Update parameters theta
    theta_gdOLS = theta_gdOLS - eta*OLSgrad
    theta_gdRidge = theta_gdRidge - eta*grad_Ridge
# After the loop, theta contains the fitted coefficients


print("Gradient Descent OLS coefficients:", theta_gdOLS)
print("Gradient Descent Ridge coefficients:", theta_gdRidge)

Gradient Descent OLS coefficients: [ 2. -1.  5.]
Gradient Descent Ridge coefficients: [ 1.99693355 -0.93151948  4.85545002]


### 4a)

Discuss the results as function of the learning rate parameters and the number of iterations.

We get closer to the analytical expression the more times we iterate. This makes sense because the new value gets updated closer and closer to the minima of the convex curve thus finding more and more optimal parameters. The higher the learning rate, the faster we reach the minima untill the learning rate is so high that the theta value skips the minima and will either occilate around minima or just skip it every iteration. It seems like this valie is between eta = 2.2 and 2.3.

### 4b)

Try to add a stopping parameter as function of the number iterations and the difference between the new and old $\theta$ values. How would you define a stopping criterion?

In [427]:
theta_gdOLS = np.ones(p)
theta_gdRidge = np.ones(p)
printed = False
DoneRigde = [np.array([100, 100, 100])]
for i in range(num_iters):
    # Compute gradients for OSL and Ridge
    OLSgrad = grad_OLS(X, y, theta_gdOLS )
    grad_Ridge = grad_RIGDE(X, y ,theta_gdRidge, lmbda)
    # Update parameters theta
    theta_gdOLS = theta_gdOLS - eta*OLSgrad
    theta_gdRidge = theta_gdRidge - eta*grad_Ridge

    #Stopping parameter
    Oldtheta = theta_gdOLS - eta*OLSgrad
    Oldrigde = theta_gdRidge - eta*grad_Ridge
    change_OLS = np.linalg.norm(theta_gdOLS - Oldtheta) #Change between thetas dependence
    change_Rigde = np.linalg.norm(theta_gdRidge - Oldrigde)
    Stop = (i+1)**-5 #Itereation dependence
    tol = 10**-4
    DoneRigde.append(theta_gdRidge)

    if change_Rigde < Stop/change_Rigde and not printed:
       print("Number of iterations intill satisfied (Rigde): ",i)
       DoneRigde.insert(0,theta_gdRidge)
       printed = True

    if DoneRigde[0][0] - theta_gdOLS[0] < tol: #Standarized for rigde change for comparison
       print("Number of iterations intill satisfied (OLS): ",i)
       DoneOLS = theta_gdOLS
       break

print("Gradient Descent OLS coefficients:", DoneOLS)
print("Gradient Descent Ridge coefficients:", DoneRigde[0])


print(theta_gdOLS[0])





Number of iterations intill satisfied (Rigde):  85
Number of iterations intill satisfied (OLS):  85
Gradient Descent OLS coefficients: [ 2.00086489 -1.          4.99960201]
Gradient Descent Ridge coefficients: [ 1.99705563 -0.93151948  4.85539385]
2.0008648914334906


## Exercise 5, Ridge regression and a new Synthetic Dataset

We create a synthetic linear regression dataset with a sparse
underlying relationship. This means we have many features but only a
few of them actually contribute to the target. In our example, we’ll
use 10 features with only 3 non-zero weights in the true model. This
way, the target is generated as a linear combination of a few features
(with known coefficients) plus some random noise. The steps we include are:

Decide on the number of samples and features (e.g. 100 samples, 10 features).
Define the **true** coefficient vector with mostly zeros (for sparsity). For example, we set $\hat{\boldsymbol{\theta}} = [5.0, -3.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0]$, meaning only features 0, 1, and 6 have a real effect on y.

Then we sample feature values for $\boldsymbol{X}$ randomly (e.g. from a normal distribution). We use a normal distribution so features are roughly centered around 0.
Then we compute the target values $y$ using the linear combination $\boldsymbol{X}\hat{\boldsymbol{\theta}}$ and add some noise (to simulate measurement error or unexplained variance).

Below is the code to generate the dataset:

In [428]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(0)

# Define dataset size
n_samples = 100
n_features = 10

# Define true coefficients (sparse linear relationship)
theta_true = np.array([5.0, -3.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0])

# Generate feature matrix X (n_samples x n_features) with random values
X = np.random.randn(n_samples, n_features)  # standard normal distribution

# Generate target values y with a linear combination of X and theta_true, plus noise
noise = 0.5 * np.random.randn(n_samples)    # Gaussian noise
y = (X @ theta_true) + noise
# Gradient descent parameters, learning rate eta first
eta = 0.1
# Then number of iterations
num_iters = 100

# Initialize weights for gradient descent

theta_gdOLS = np.ones(n_features)
theta_gdRidge = np.ones(n_features)
# Gradient descent loop

for i in range(num_iters):
    # Compute gradients for OSL and Ridge
    OLSgrad = grad_OLS(X, y, theta_gdOLS )
    grad_Ridge = grad_RIGDE(X, y ,theta_gdRidge, lmbda)
    # Update parameters theta
    theta_gdOLS = theta_gdOLS - eta*OLSgrad
    theta_gdRidge = theta_gdRidge - eta*grad_Ridge


    #Stopping parameter
    Oldtheta = theta_gdOLS - eta*OLSgrad
    Oldrigde = theta_gdRidge - eta*grad_Ridge
    change_OLS = np.linalg.norm(theta_gdOLS - Oldtheta) #Change between thetas dependence
    change_Rigde = np.linalg.norm(theta_gdRidge - Oldrigde)

    Stop = (i+1)**-6 #Itereation dependence
   
    if change_Rigde < Stop/change_OLS and not printed: 
       print("Number of iterations intill satisfied (OLS): ",i)
       printed = True
    if change_OLS < Stop/change_OLS: #Standarized for rigde change for comparison
       print("Number of iterations intill satisfied (Rigde): ",i)
       break
     
print("Gradient Descent OLS coefficients:", theta_gdOLS)
print("Gradient Descent Ridge coefficients:", theta_gdRidge)
  

I = np.eye(n_features)
lmbda = 0.1

theta_closed_formOLS = np.linalg.inv(X.T @ X) @ (X.T @ y)
theta_closed_formRidge = np.linalg.inv((X.T @ X)+(lmbda*I)) @ (X.T @ y)

print("Closed-form Ridge coefficients:", theta_closed_formOLS)
print("Closed-form OLS coefficients:", theta_closed_formRidge)


Number of iterations intill satisfied (Rigde):  97
Gradient Descent OLS coefficients: [ 5.00905236e+00 -3.00382930e+00 -1.62713728e-02  1.44822183e-01
 -7.16036678e-02 -4.29685812e-02  2.05557709e+00  1.97535221e-03
  4.11914144e-02 -5.10222192e-02]
Gradient Descent Ridge coefficients: [ 4.56106734 -2.64148831 -0.01936489  0.19520474 -0.14478459 -0.10738746
  1.8165109   0.02712841 -0.03893852 -0.05635538]
Closed-form Ridge coefficients: [ 5.00905318e+00 -3.00383337e+00 -1.62718294e-02  1.44819819e-01
 -7.16006510e-02 -4.29656382e-02  2.05558117e+00  1.97583716e-03
  4.11922237e-02 -5.10225177e-02]
Closed-form OLS coefficients: [ 5.00410898e+00 -2.99968373e+00 -1.63065915e-02  1.45477818e-01
 -7.25435409e-02 -4.37776623e-02  2.05285140e+00  2.26563823e-03
  4.02214213e-02 -5.10893259e-02]


This code produces a dataset where only features 0, 1, and 6
significantly influence $\boldsymbol{y}$. The rest of the features have zero true
coefficient. For example, feature 0 has
a true weight of 5.0, feature 1 has -3.0, and feature 6 has 2.0, so
the expected relationship is:

$$
y \approx 5 \times x_0 \;-\; 3 \times x_1 \;+\; 2 \times x_6 \;+\; \text{noise}.
$$

You can remove the noise if you wish to. 

Try to fit the above data set using OLS and Ridge regression with the analytical expressions and your own gradient descent codes.

If everything worked correctly, the learned coefficients should be
close to the true values [5.0, -3.0, 0.0, …, 2.0, …] that we used to
generate the data. Keep in mind that due to regularization and noise,
the learned values will not exactly equal the true ones, but they
should be in the same ballpark.  Which method (OLS or Ridge) gives the best results?

Answer: I found the OLS to clearly outperform at GD but both analytical expressions was quite precise, with Rigde being slightly more precise.